redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, :only => [:new, :create]
  resources :agile_versions, :only => [:index] do
    post :index, :on => :collection
  end
end

resources :agile_versions, :only => [:update, :show] do
  collection do
    get 'load'
    get 'autocomplete'
  end
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
end

resources :agile_queries

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'

redmine_agile/app/controllers/agile_versions_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileVersionsController < ApplicationController
  unloadable

  menu_item :agile
  
  before_filter :find_project_by_project_id, :only => [:index, :autocomplete, :load]
  before_filter :find_version, :only => [:load]
  before_filter :authorize, :except => [:autocomplete, :load]
  before_filter :find_no_version_issues, :only => [:index, :autocomplete]

  include QueriesHelper
  helper :queries
  include RedmineAgile::AgileHelper

  def index
    retrieve_versions_query
      @backlog_version = @query.backlog_version
      @backlog_version_issues =  @query.backlog_version_issues

      @current_version = @query.current_version
      @current_version_issues = @query.current_version_issues
    respond_to do |format|
      format.html
      format.js
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def autocomplete
    render :layout => false
  end

  def load
    retrieve_versions_query
    @version_issues = @query.version_issues(@version)
    @version_type = params[:version_type]
    @other_version_type = @version_type == "backlog" ? "current" : "backlog"
    @other_version_id = params[:other_version_id]
    respond_to do |format|
      format.js
    end
  end

  private

  def find_version
    @version = Version.visible.find(params[:version_id])
    @project ||= @version.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_no_version_issues
    retrieve_versions_query
      scope = @query.no_version_issues(params)
      @issue_count = scope.count
      @issue_pages = Redmine::Pagination::Paginator.new @issue_count, 20, params['page']
      @version_issues = scope.offset(@issue_pages.offset).limit(@issue_pages.per_page).all
  end

end

redmine_agile/app/helpers/agile_versions_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

module AgileVersionsHelper
  def version_select_tag(version, option={})
    return "" if version.blank?
    version_id =  version.is_a?(Version) && version.id || version
    other_version_id = option[:other_version].is_a?(Version) && option[:other_version].id || option[:other_version]
    select_tag('version_id',
      options_for_select(versions_collection_for_select,
          {:selected => version_id, :disabled => other_version_id}),
      :data => {:remote => true,
                :method => 'get',
                :url => load_agile_versions_path(:version_type => option[:version_type],
                                                 :other_version_id => other_version_id,
                                                 :project_id => @project)}) +
    content_tag(:span, '', :class => "hours header-hours #{option[:version_type]}-hours")
  end

  def versions_collection_for_select
    @project.shared_versions.open.map{|version| [format_version_name(version), version.id.to_s]}
  end

  def estimated_hours(issue)
    "%.2fh" % issue.estimated_hours.to_f
  end
end

redmine_agile/app/views/agile_versions/_board.html.erb
<%= form_tag({}) do -%>
  <%= hidden_field_tag 'back_url', url_for(params) %>
  <%= hidden_field_tag 'project_id', @project.id if @project %>
<div class="autoscroll">
    <div class="flash error" style="display: none;" id="agile-board-errors">
    </div>
    <table class="list  versions-planning-board">
      <thead>
      <tr>
        <th style="width: 33%; text-align: left;">
          <%= text_field_tag "search", '', :placeholder => l(:label_agile_no_version_issues) %>
          <%= javascript_tag "observeIssueSearchfield('search', '#{escape_javascript autocomplete_agile_versions_path(:project_id => @project)}');" %>
        </th>
        <th style="width: 33%; text-align: left;" id="backlog_version_header">
          <%= version_select_tag(@backlog_version, :version_type => "backlog", :other_version => @current_version) %>
        </th>
        <th style="width: 33%; text-align: left;" id="current_version_header">
          <%= version_select_tag(@current_version, :version_type => "current", :other_version => @backlog_version) %>
        </th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <td id="no_version" class="issue-version-col" data-id="">
          <%= render :partial => 'version_issues', :object => @version_issues  %>
          </td>
          <td id="backlog_version" class="<%= 'issue-version-col' if @backlog_version %>" data-id="<%= @backlog_version && @backlog_version.id %>">
            <%= render :partial => 'version_issues', :object => @backlog_version_issues if @backlog_version %>
          </td>
          <td id="current_version" class="<%= 'issue-version-col' if @current_version %>" data-id="<%= @current_version && @current_version.id %>">
            <%= render :partial => 'version_issues', :object => @current_version_issues if @current_version %>
          </td>
        </tr>
      </tbody>
    </table>
</div>

<% end %>

<%= javascript_tag do %>
  recalculateHours();
  $(document).ajaxSuccess(recalculateHours);
<% end %>

redmine_agile/app/views/agile_versions/_version_issues.html.erb
<% if version_issues.any? %>
  <% version_issues.each do |issue| %>
    <div class="issue-card hascontextmenu" data-id="<%= issue.id %>" data-estimated-hours="<%= estimated_hours(issue) %>">
      <% if issue.estimated_hours %>
        <span class="hours"><%= estimated_hours(issue) %></span>
      <% end %>
      <%= check_box_tag("ids[]", issue.id, false, :id => nil, :class => 'checkbox') %>
      <%= link_to_issue(issue, :project => (@project != issue.project)) %>
    </div>
  <% end %>

  <% if version_issues.first.fixed_version_id.blank? %>
    <div class="pagination-wrapper">
    <p class="pagination">
        <% pagination_links_full(@issue_pages, @issue_count, :per_page_links => false)  do |text, parameters, options| %>
          <%= link_to text, autocomplete_agile_versions_path(parameters.merge(:q => params[:q], :project_id => @project)), :remote => true %>
        <% end %>
    </p>
    </div>
  <% end %>
<% end %>

redmine_agile/app/views/agile_versions/autocomplete.js.erb
$('#no_version').html('<%= escape_javascript(render :partial => "version_issues", :object => @version_issues) %>')

redmine_agile/app/views/agile_versions/index.html.erb
<h2><%= l(:label_agile_version_planning) %></h2>

<% if User.current.allowed_to?(:edit_issues, @project) %>
  <%= javascript_tag do %>
    new PlanningBoard().init({
      project_id: '<%= @project && @project.id %>',
      update_agile_board_path: '<%= escape_javascript update_agile_board_path %>',
      issues_path: '<%= escape_javascript issues_path %>'
    });
  <% end %>
<% end %>

<% if @project.shared_versions.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <%= render :partial => 'board' %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'agile_boards/issues_links' %>
  <%= render :partial => 'agile_charts/agile_charts' %>
<% end %>

<% html_title l(:label_agile_version_planning) %>
<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_agile, :plugin => 'redmine_agile' %>
  <%= javascript_include_tag "jquery.ui.touch-punch.js", :plugin => 'redmine_agile' %>
  <%= stylesheet_link_tag :context_menu %>
<% end %>

redmine_agile/app/views/agile_versions/load.js.erb
$('#<%= @version_type %>_version').html('<%= escape_javascript(render :partial => "version_issues", :object => @version_issues) %>');
$('#<%= @version_type %>_version').attr('data-id', '<%= @version.id %>');

$('#<%= @version_type %>_version_header').html('<%= escape_javascript(version_select_tag(@version, :version_type => @version_type, :other_version => @other_version_id)) %>');
$('#<%= @other_version_type %>_version_header').html('<%= escape_javascript(version_select_tag(@other_version_id, :version_type => @other_version_type, :other_version => @version)) %>');