redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, :only => [:new, :create]
  resources :agile_versions, :only => [:index] do
    post :index, :on => :collection
  end
end

resources :agile_versions, :only => [:update, :show] do
  collection do
    get 'load'
    get 'autocomplete'
  end
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
end

resources :agile_queries

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'

redmine_agile/app/controllers/agile_boards_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileBoardsController < ApplicationController
  unloadable

  menu_item :agile

  before_filter :find_issue, :only => [:update, :issue_tooltip]
  before_filter :find_optional_project, :only => [:index]

  helper :issues
  helper :journals
  helper :projects
  include ProjectsHelper
  helper :custom_fields
  include CustomFieldsHelper
  helper :issue_relations
  include IssueRelationsHelper
  helper :watchers
  include WatchersHelper
  helper :attachments
  include AttachmentsHelper
  helper :queries
  include QueriesHelper
  helper :repositories
  include RepositoriesHelper
  helper :sort
  include SortHelper
  include IssuesHelper
  helper :timelog
  include RedmineAgile::AgileHelper

  def index
    retrieve_agile_query

    if @query.valid?
      @issues = @query.issues
      @issue_board = @query.issue_board
      @board_columns = @query.board_statuses
      
      if @query.has_column_name?(:day_in_state)
        @journals_for_state = Journal.joins(:details).where(
          :journals => {
            :journalized_id => @issues.map{|issue| (issue.id rescue nil)}, 
            :journalized_type => "Issue"
          }, 
          :journal_details => {:prop_key => 'status_id'}).order("created_on DESC") 
      end

      respond_to do |format|
        format.html { render :template => 'agile_boards/index', :layout => !request.xhr? }
        format.js
      end
    else
      respond_to do |format|
        format.html { render(:template => 'agile_boards/index', :layout => !request.xhr?) }
        format.js
      end
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def update
    (render_403; return false) unless @issue.editable?
    retrieve_agile_query_from_session
    @issue.init_journal(User.current)
    @issue.safe_attributes = params[:issue]
    saved = params[:issue] && params[:issue].inject(true) do |total, attribute|
       total &&= @issue.attributes[attribute.first].to_i == attribute.last.to_i
    end
    call_hook(:controller_agile_boards_update_before_save, { :params => params, :issue => @issue})
    @update = true
    if saved && @issue.save
      call_hook(:controller_agile_boards_update_after_save, { :params => params, :issue => @issue})
      AgileRank.transaction do
        Issue.eager_load(:agile_rank).find(params[:positions].keys).each do |issue|
          issue.agile_rank.position = params[:positions][issue.id.to_s]['position']
          issue.agile_rank.save
        end
      end if params[:positions]
      respond_to do |format|
        format.html { render(:partial => 'issue_card', :locals => {:issue => @issue}, :status => :ok, :layout => nil) }
      end
    else
      respond_to do |format|
        messages = @issue.errors.full_messages
        messages = [l(:text_agile_move_not_possible)] if messages.empty?
        format.html { render :json => messages, :status => :fail, :layout => nil }
      end
    end
  end

  def issue_tooltip
    render :partial => 'issue_tooltip'
  end

end

redmine_agile/app/helpers/agile_boards_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

module AgileBoardsHelper
  def agile_color_class(issue, options={})
    ''
      end

  def agile_user_color(login, options={})
  end

  def header_th(name, rowspan = 1, colspan = 1, leaf = nil)
    th_attributes = {}
    if leaf
      th_attributes[:"data-column-id"] = leaf.id
      issue_count = leaf.instance_variable_get("@issue_count")
      count_tag = " (#{content_tag(:span, issue_count.to_i, :class => 'count')})".html_safe
      # estimated hours total
      hours_count = leaf.instance_variable_get("@estimated_hours_sum") || 0
      hours_tag = " #{content_tag(:span, ("%.2fh" % hours_count.to_f).to_s, :class => 'hours', :title => l(:field_estimated_hours))}".html_safe if hours_count > 0
    end
    content_tag :th, h(name) + count_tag + hours_tag, th_attributes
  end

  def render_board_headers(columns)
    "<tr>#{columns.map{|column| header_th(column.name, 1, 1, column)}.join}</tr>".html_safe
      end

  def color_by_name(name)
    "##{"%06x" % (name.unpack('H*').first.hex % 0xffffff)}"
  end

  def render_board_fields_selection(query)
    query.available_inline_columns.reject(&:frozen?).map do |column|
      label_tag('', check_box_tag('c[]', column.name, query.columns.include?(column)) + column.caption, :class => "floating" )
    end.join(" ").html_safe
  end

  def render_issue_card_hours(query, issue)
    hours = []
    hours << "%.2f" % issue.total_spent_hours.to_f if query.has_column_name?(:spent_hours) && issue.total_spent_hours > 0
    hours << "%.2f" % issue.estimated_hours.to_f if query.has_column_name?(:estimated_hours) && issue.estimated_hours
    content_tag(:span, "(#{hours.join('/')}h)", :class => 'hours') unless hours.blank?
  end

  def agile_progress_bar(pcts, options={})
    pcts = [pcts, pcts] unless pcts.is_a?(Array)
    pcts = pcts.collect(&:round)
    pcts[1] = pcts[1] - pcts[0]
    pcts << (100 - pcts[1] - pcts[0])
    width = options[:width] || '100px;'
    legend = options[:legend] || ''
    content_tag('table',
      content_tag('tr',
        (pcts[0] > 0 ? content_tag('td', '', :style => "width: #{pcts[0]}%;", :class => 'closed') : ''.html_safe) +
        (pcts[1] > 0 ? content_tag('td', '', :style => "width: #{pcts[1]}%;", :class => 'done') : ''.html_safe) +
        (pcts[2] > 0 ? content_tag('td', '', :style => "width: #{pcts[2]}%;", :class => 'todo') : ''.html_safe) +
        (legend ? content_tag('td', content_tag('p', legend, :class => 'percent'), :class => 'legend') : ''.html_safe)
      ), :class => "progress progress-#{pcts[0]}", :style => "width: #{width};").html_safe
  end

  def issue_children(issue)
    return unless issue.children.any?
    content_tag :ul do
      issue.children.select{ |x| x.visible? }.each do |child|
        id = if @query.has_column_name?(:tracker) || @query.has_column_name?(:id) then "##{child.id}:&nbsp;" else '' end
        concat "<li class='#{'task-closed' if child.closed?}'><a href='#{issue_path(child)}'>#{id}#{child.subject}</a></li>#{issue_children(child)}".html_safe
      end
    end
  end

  def time_in_state(distance=nil)
    return "" if !distance || !(distance.is_a? Time)
    distance = Time.now - distance
    hours = distance/(3600)
    return "#{I18n.t('datetime.distance_in_words.x_hours', :count => hours.to_i)}" if hours < 24
    "#{I18n.t('datetime.distance_in_words.x_days', :count => (hours/24).to_i)}"
  end

  def class_for_closed_issue(issue)
    return '' if !RedmineAgile.hide_closed_issues_data?
    return 'closed-issue' if issue.closed?
    ''
  end

  def init_agile_tooltip_info
    javascript_tag "function callGetToolTipInfo()
      {
        var url = '#{issue_tooltip_url}';
        getToolTipInfo(this, url);
      }
      $('.tooltip').mouseenter(callGetToolTipInfo);
    "
  end

end

redmine_agile/app/views/agile_boards/_board.html.erb
<%= form_tag({}) do -%>
  <%= hidden_field_tag 'back_url', url_for(params) %>
  <%= hidden_field_tag 'project_id', @project.id if @project %>
  <% board_statuses = IssueStatus.sorted %>
<div class="agile-board autoscroll">
    <div class="flash error" style="display: none;" id="agile-board-errors">
    </div>
    <table class="list issues-board <%= 'status-colors' if RedmineAgile.status_colors? %> <%= 'minimize-closed' if RedmineAgile.minimize_closed? %>">
      <thead>
      <%= render_board_headers(@board_columns) %>
      </thead>
          <tr style="text-align: center;white-space: nowrap;" class="issue <%= cycle('odd', 'even') %>">
          <% @board_columns.each do |column| %>
            <td class="issue-status-col <%= 'closed' if column.is_closed? %>" data-id="<%= column.id %>">
            <% @issue_board[[column.id]].to_a.each do |issue| %>
              <%= render :partial => 'issue_card', :locals => {:issue => issue} %>
            <% end %>
            </td>

            <% end %>
          </tr>

    </table>
</div>

<% end %>

redmine_agile/app/views/agile_boards/_index.html.erb
<% if User.current.allowed_to?(:edit_issues, @project, :global => true) %>
  <script type="text/javascript">
    new AgileBoard().init({
      project_id: '<%= @project && @project.id %>',
      update_agile_board_path: '<%= escape_javascript update_agile_board_path %>',
      issues_path: '<%= escape_javascript issues_path %>'
    });

    document.onkeydown = function(evt) {
        evt = evt || window.event;
        if (evt.keyCode == 27) {
            $('html.agile-board-fullscreen').removeClass('agile-board-fullscreen');
            $(".issue-card").addClass("hascontextmenu");
        }
    };
  </script>
<% end %>


<div class="contextual">
<% if !@query.new_record? && @query.editable_by?(User.current) %>
  <%= link_to l(:button_edit), edit_agile_query_path(@query), :class => 'icon icon-edit' %>
  <%= delete_link agile_query_path(@query) %>
<% end %>
</div>

<h2><%= @query.new_record? ? l(:label_agile_board) : h(@query.name) %></h2>
<% html_title(@query.new_record? ? l(:label_agile_board) : @query.name) %>

<%= form_tag({ :controller => 'agile_boards', :action => 'index', :project_id => @project },
            :method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
        <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
        <div style="<%= @query.new_record? ? "" : "display: none;" %>">
          <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
        </div>
      </fieldset>
      <fieldset class="collapsible collapsed">
        <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
        <div style="display: none;">
          <table class="options">
            <tr>
              <td><%= l(:label_agile_fields) %></td>
              <td class="card-fields">
                <%= render_board_fields_selection(@query) %>
              </td>
            </tr>
          </table>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    </p>

  </div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <% if @issues.empty? || @board_columns.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <% if @query.truncated %>
      <p class="warning"><%= l(:label_agile_board_truncated, :max => RedmineAgile.board_items_limit) %></p>
    <% end %>
    <%= render :partial => 'board' %>
  <% end %>
<% end %>

<% content_for :sidebar do %>
 
  <%= render :partial => 'upgrade_to_pro' %>
 
  <%= render :partial => 'issues_links' %>
  <% if @project && @project.assignable_users.any? %>
    <%= render :partial => 'members' %>
  <% end %>
  <%= render :partial => 'agile_charts/agile_charts' %>
<% end %>

<% html_title l(:label_agile_board) %>
<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_agile, :plugin => 'redmine_agile' %>
  <%= javascript_include_tag "jquery.ui.touch-punch.js", :plugin => 'redmine_agile' %>
  <%= stylesheet_link_tag :context_menu %>
  <%= stylesheet_link_tag "redmine_agile.css", :plugin => "redmine_agile", :media => "print" %>
<% end %>

redmine_agile/app/views/agile_boards/_issue_card.html.erb
<div class="issue-card hascontextmenu <%= agile_color_class(issue, :color_base => @query.respond_to?(:color_base) && @query.color_base) %> <%= class_for_closed_issue(issue) %>" data-id="<%= issue.id %>" style="<%= agile_user_color(issue.assigned_to.login, :color_base => @query.respond_to?(:color_base) && @query.color_base) if issue.assigned_to %>">
    <% if issue.closed? && RedmineAgile.hide_closed_issues_data? %>
      <span class="fields">
         <div class="tooltip">
           <p class="issue-id <%= 'without-tracker' if @query.has_column_name?(:tracker).blank? %>">
               <strong><%= link_to "#{'#' + issue.id.to_s}", issue_path(issue) %></strong>
            </p>
            <span class="tip">
            </span>
          </div>
      </span>
    <% else %>
      <span class="fields">
          <% if @query.has_column_name?(:project) %>
            <p class="project">
              <%= issue.project.name %>
            </p>
          <% end %>
          <p class="issue-id <%= 'without-tracker' if @query.has_column_name?(:tracker).blank? %>">
            <%= check_box_tag("ids[]", issue.id, false, :id => nil, :class => 'checkbox') %>
            <% if @query.has_column_name?(:tracker) %>
              <strong><%= issue_heading(issue) %></strong>
            <% end %>
            <%= render_issue_card_hours(@query, issue) %>
          </p>
          <p class="name" ><%= link_to "#{'#' + issue.id.to_s + ': ' if @query.has_column_name?(:id) && @query.has_column_name?(:tracker).blank?}#{issue.subject.truncate(100)}", issue_path(issue) %></p>
          <p class="attributes">
            <% @query.card_columns.select{|c| !c.value(issue).blank? }.each do |column| %>
              <b><%= column.caption %></b>: <%= column_content(column, issue) %> <br>
            <% end %>
          </p>

          <% if @query.has_column_name?(:day_in_state) %>
            <p class="attributes">
                <b><%= " #{I18n.t('label_agile_day_in_state')}: " %></b>
                <% find_change_state = false %>
                <% if @journals_for_state %>
                  <% @journals_for_state.each do |journal| %>
                    <% if journal.journalized_id == issue.id %>
                      <%= time_in_state(journal.created_on) %>
                      <% find_change_state = true %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% end %>

                <% if !find_change_state %>
                  <%= time_in_state(issue.day_in_state) %>
                <% end %>
            </p>
          <% end %>

          <% if @query.has_column_name?(:description) && !issue.description.blank? %>
            <em class="info description">
              <%= issue.description.truncate(200) %>
            </em>
          <% end %>
          <% if @query.has_column_name?(:sub_issues) && issue.sub_issues.any? %>
            <div class='sub-issues'>
              <%= issue_children(issue) %>
            </div>
          <% end %>
          <% if @query.has_column_name?(:thumbnails)  %>
            <% image = issue.attachments.select(&:thumbnailable?).last %>
            <% if image %>
            <div class="thumbnail" style="background-image: url('<%= thumbnail_path(image, :size => 250) %>')">
            </div>
            <% end %>
          <% end %>
          <% if @query.has_column_name?(:assigned_to) %>
            <p class="info" style="<%= 'display: none;' unless issue.assigned_to %>">
              <span class="user"><%= avatar(issue.assigned_to, :size => "14").to_s.html_safe + " " + link_to_user(issue.assigned_to) if issue.assigned_to %></span>
            </p>
          <% end %>


          <% if @query.has_column_name?(:done_ratio) %>
            <%= progress_bar(issue.done_ratio, :width => '100%') %>
          <% end %>
      </span>
    <% end %>
</div>
<% if User.current.allowed_to?(:edit_issues, @project, :global => true) && @update %>
  <script type="text/javascript">
    new AgileBoard().init({
      project_id: '<%= @project && @project.id %>',
      update_agile_board_path: '<%= escape_javascript update_agile_board_path %>',
      issues_path: '<%= escape_javascript issues_path %>'
    });

    document.onkeydown = function(evt) {
        evt = evt || window.event;
        if (evt.keyCode == 27) {
            $('html.agile-board-fullscreen').removeClass('agile-board-fullscreen');
            $(".issue-card").addClass("hascontextmenu");
        }
    };

    if ($('html').hasClass('agile-board-fullscreen')) {
      $(".issue-card[data-id=<%= issue.id %>]").removeClass("hascontextmenu");
    };
  </script>
  <%= init_agile_tooltip_info %>
<% end %>

redmine_agile/app/views/agile_boards/_issue_tooltip.html.erb
<%= render_issue_tooltip @issue %>

redmine_agile/app/views/agile_boards/_issues_links.html.erb
<h3><%= l(:label_issue_plural) %></h3>

  <ul>
  <li><%= link_to l(:label_issue_view_all), _project_issues_path(@project, :set_filter => 1) %></li>
  <% if @project %>
  <li><%= link_to l(:field_summary), project_issues_report_path(@project) %></li>
  <% end %>

  <% if User.current.allowed_to?(:view_calendar, @project, :global => true) %>
  <li><%= link_to l(:label_calendar), _project_calendar_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_gantt, @project, :global => true) %>
  <li><%= link_to l(:label_gantt), _project_gantt_path(@project) %></li>
  <% end %>
  <% if User.current.allowed_to?(:view_agile_queries, @project) %>
  <li><%= link_to l(:label_agile_board), {:controller => "agile_boards", :action => "index", :project_id => @project} %></li>
  <% end %>
  <% if User.current.allowed_to?(:manage_agile_verions, @project) %>
  <li><%= link_to l(:label_agile_version_planning), {:controller => "agile_versions", :action => "index", :project_id => @project} %></li>
  <% end %>
  </ul>

redmine_agile/app/views/agile_boards/_issues_sidebar.html.erb
<% if User.current.allowed_to?(:view_agile_queries, @project, :global => true) %>
  <%= link_to l(:label_agile_board), {:controller => "agile_boards", :action => "index", :project_id => @project} %>
  <br>
<% end %>
<% if User.current.allowed_to?(:manage_agile_verions, @project) && @project.versions.open.any? %>
  <%= link_to l(:label_agile_version_planning), {:controller => "agile_versions", :action => "index", :project_id => @project} %>
  <br>
<% end %>

redmine_agile/app/views/agile_boards/_members.html.erb
<div class="project-members">
  <h3><%=l(:label_member_plural)%></h3>
    <% @project.assignable_users.each do |user| %>
      <span class="assignable-user" data-id="<%= user.id %>"><%= avatar(user.is_a?(User) ? user : '<gravatar>', :size => "14", :style => agile_user_color(user.login, :color_base => @query.respond_to?(:color_base) && @query.color_base) ).to_s.html_safe + " " + link_to_user(user) %>
      <br>
      </span>
    <% end %>
</div>

redmine_agile/app/views/agile_boards/_upgrade_to_pro.html.erb
<h3><%= l(:label_agile_light_free_version) %></h3>
<ul>
  <li><%= link_to l(:label_agile_link_to_pro), "http://www.redminecrm.com/projects/agile/pages/last?from=light_upgrade" %>
</li>
<li><%= link_to l(:label_agile_link_to_pro_demo), "http://demo.redminecrm.com/projects/agile/agile/board?query_id=4?from=light_live_preview" %>
</li>
<li><%= link_to l(:label_agile_link_to_more_plugins), "http://www.redminecrm.com/pages/plugins?from=light_more_plugins" %>
</li>
</ul>

redmine_agile/app/views/agile_boards/index.html.erb
<%= render 'index' %>
<%= init_agile_tooltip_info %>

redmine_agile/app/views/agile_boards/index.js.erb
$('#content').html('<%= j(render('index')) %>')
$('table.issues-board').StickyHeader();
<%= init_agile_tooltip_info %>

redmine_agile/app/views/agile_boards/update.js.erb
decHtmlNumber('th[data-column-id="<%= params[:old_status_id] %>"] span.count');
incHtmlNumber('th[data-column-id="<%= params[:new_status_id] %>"] span.count');
decHtmlNumber('tr.group.swimlane[data-id="<%= params[:old_swimlane_id] %>"] td span.count');
incHtmlNumber('tr.group.swimlane[data-id="<%= params[:new_swimlane_id] %>"] td span.count');

//$('.issue-card[data-id="<%= @issue.id %>"]').html("<%= render :partial => 'issue_card', :locals => {:issue => @issue} %>");