redmine_agile/config/routes.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :agile_queries, :only => [:new, :create]
  resources :agile_versions, :only => [:index] do
    post :index, :on => :collection
  end
end

resources :agile_versions, :only => [:update, :show] do
  collection do
    get 'load'
    get 'autocomplete'
  end
end

resources :issues do
  get "done_ratio", :to => "agile_journal_details#done_ratio"
  get "status", :to => "agile_journal_details#status"
  get "assignee", :to => "agile_journal_details#assignee"
end

resources :agile_queries

get '/projects/:project_id/agile/charts', :to => "agile_charts#show", :as => "project_agile_charts"
get '/agile/charts/', :to => "agile_charts#show", :as => "agile_charts"
get '/agile/charts/render_chart', :to => "agile_charts#render_chart"
get '/agile/charts/select_version_chart', :to => "agile_charts#select_version_chart"
get '/projects/:project_id/agile/board', :to => 'agile_boards#index'
get '/agile/board', :to => 'agile_boards#index'
put '/agile/board', :to => 'agile_boards#update', :as => 'update_agile_board'
get '/agile/issue_tooltip', :to => 'agile_boards#issue_tooltip', :as => 'issue_tooltip'

redmine_agile/app/controllers/agile_journal_details_controller.rb
# This file is a part of Redmin Agile (redmine_agile) plugin,
# Agile board plugin for redmine
#
# Copyright (C) 2011-2015 RedmineCRM
# http://www.redminecrm.com/
#
# redmine_agile is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_agile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_agile.  If not, see <http://www.gnu.org/licenses/>.

class AgileJournalDetailsController < ApplicationController
  unloadable

  before_filter :find_issue

  helper :issues

  def done_ratio
    @done_ratios = @issue.journals.map(&:details).flatten.select {|detail| 'done_ratio' == detail.prop_key }.sort_by {|a| a.journal.created_on }
  end

  def status
    @statuses = @issue.journals.map(&:details).flatten.select {|detail| 'status_id' == detail.prop_key }.sort_by {|a| a.journal.created_on }
  end

  def assignee
    @assignees = @issue.journals.map(&:details).flatten.select {|detail| 'assigned_to_id' == detail.prop_key }.sort_by {|a| a.journal.created_on }
  end

  def edit
  end

  def new
  end

  private

  def find_issue
    @issue = Issue.eager_load(:journals => :details).find(params[:issue_id])
    raise Unauthorized unless @issue.visible?
    @project = @issue.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

redmine_agile/app/views/agile_journal_details/assignee.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:field_assigned_to) %>

<% html_title(l(:field_assigned_to)) %>

<% if @assignees.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_assigned_to) %></th>
      <th><%= l(:field_author) %></th>
  </tr></thead>
  <% @assignees.each_with_index do |status, index| %>
  <% assignee = User.where(:id => status.value).first %>
  <tr class="<%= cycle('odd', 'even') %>">
      <td class="index"><%= index + 1 %></td>
      <td class="name"><%= format_time(status.journal.created_on) %></td>
      <td class="name"><%= avatar(assignee, :size => "14").to_s.html_safe + " " + link_to_user(assignee) %></td>
      <td><%= link_to_user status.journal.user %></td>
  </tr>
  <% end %>
  </table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

redmine_agile/app/views/agile_journal_details/done_ratio.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:field_done_ratio) %>

<% html_title(l(:field_done_ratio)) %>

<% if @done_ratios.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_done_ratio) %></th>
      <th><%= l(:label_agile_charts_number_of_hours) %></th>
      <th><%= l(:field_author) %></th>
  </tr></thead>
  <% @done_ratios.each_with_index do |done_ratio, index| %>
  <tr class="<%= cycle('odd', 'even') %>">
      <td class="index"><%= index + 1 %></td>
      <td class="name"><%= format_time(done_ratio.journal.created_on) %></td>
      <td><%= progress_bar(done_ratio.value.to_f, :width => '80px', :legend => "#{"%.2f" %done_ratio.value.to_f}%") %></td>
      <td><%= "%.2f" % (@issue.estimated_hours.to_f * (100 - done_ratio.value.to_f) / 100.0) %></td>
      <td><%= done_ratio.journal.user.name %></td>
  </tr>
  <% end %>
  </table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

redmine_agile/app/views/agile_journal_details/edit.html.erb
<h2>AgileDoneRatioFlowsController#edit</h2>

redmine_agile/app/views/agile_journal_details/new.html.erb
<h2>AgileDoneRatioFlowsController#new</h2>

redmine_agile/app/views/agile_journal_details/status.html.erb
<%= title [issue_heading(@issue) , issue_path(@issue)],  l(:label_issue_status) %>

<% html_title(l(:label_issue_status_plural)) %>

<% if @statuses.any? %>
  <table class="list"><thead>
  <tr>
      <th>#</th>
      <th><%= l(:field_created_on) %></th>
      <th><%= l(:field_status) %></th>
      <th><%= l(:field_author) %></th>
  </tr></thead>
  <% @statuses.each_with_index do |status, index| %>
  <% issue_status = IssueStatus.where(:id => status.value).first %>
  <tr class="<%= cycle('odd', 'even') %>">
      <td class="index"><%= index + 1 %></td>
      <td class="name"><%= format_time(status.journal.created_on) %></td>
      <td><%= issue_status.name %></td>
      <td><%= status.journal.user.name %></td>
  </tr>
  <% end %>
  </table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>